### ISSUE TITLE
Add spell-checker

### ISSUE THREAD

**Issue by mark-wiemer** [luanti-org/docs.luanti.org#83]
Overall, no need to be strict here about American vs British English or including variable names in a dict vs ignoring them each time they come up. Instead, let's focus on integrating an automated check that works so devs can quickly scan files and publish them with confidence.

- CI fails if words are marked as spelled incorrectly
- Contributors can easily update the list of known words
- Contributors can easily ignore entire files if they want to
- Contributors can easily identify words marked as spelled incorrectly via their IDE as a standard info squiggle (similar to warnings)

---

Words that can probably be changed:

- [ ] unittests -> unit tests
- [ ] coredev -> core dev
- [ ] toolcaps -> tool caps?
- [ ] crossview -> cross-view

Future considerations:

- [x] style guide entry on American vs British vs "other" English? We prefer American English but want to avoid idioms. Out of scope for this issue, accepting any common spelling of a word is OK for now.

**Comment by mark-wiemer** [comment]
Yep, working on this now using https://streetsidesoftware.com/vscode-spell-checker/, bumped into https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/issues/1081 though :(

**Comment by mark-wiemer** [comment]
```log
CSpell: Files checked: 89, Issues found: 3343 in 86 files.
```

Well, at least it's working locally :)

**Comment by wsor4035** [comment]
ci shouldnt be added till https://github.com/minetest/dev.luanti.org/issues/15 is done

**Comment by mark-wiemer** [comment]
Fair enough

**Comment by wsor4035** [comment]
@mark-wiemer is there anything blocking cspell from being a ci action now and closing this issue?

**Comment by mark-wiemer** [comment]
There are still hundreds of outstanding warnings

**Comment by mark-wiemer** [comment]
[cspell as a Go module](https://pkg.go.dev/github.com/jason3s/cspell) is a thing, but ultimately it's the same code with the same dependencies. I know dependency hell is a common problem with npm, but I imagine Go just... hides it better? Happy to explore alternatives if folks think there may be value. Gonna work on fixing typos for now.

**Comment by mark-wiemer** [comment]
With #188, we're down to:

CSpell: Files checked: 148, Issues found: 720 in 73 files.

**Comment by mark-wiemer** [comment]
Down to 327 issues with #195 :)
